### ISSUE TITLE
Publish to npm?

### ISSUE THREAD

**Issue by rowanc1** [benrbray/prosemirror-math#8]
Really like the approach that you have taken here! I am thinking about integrating something like this to our project https://github.com/curvenote/editor which needs better math support. :)

I don't think that you have published this yet to npm? Do you have plans to?

I think there would also need to be a bit of a distinction between the current index, which is a demo if I am not mistaken, and exposing the relevant plugins to another prosemirror implementation.

Happy to help if you are going in this direction!

**Comment by benrbray** [comment]
Thanks for your interest!  Since this project has been getting some interest lately, now seems like a good time to work towards an npm release!  

I'll use this issue to take down some of my initial thoughts.  This will be my first time publishing an npm package, so any help / feedback would be most welcome :).

I will need to resolve the following tasks / questions before the first release:

- [ ] Export the relevant ProseMirror plugins directly, and move the demo code elsewhere (to a new branch?  to a new repository?  to a folder ignored by npm?  I'm not sure what the best approach is).
    - This should resolve #7 as well.
- [ ] I should replace `parcel` with either `webpack` or `rollup` for the npm release
    - I'm more familiar with webpack, but based on a quick search it appears that rollup might be more appropriate for npm packages
- [ ] Any ProseMirror packages that the `prosemirror-math` plugin depends on should probably be listed as `peerDependencies` in the `package.json` file.
- [ ] Make sure the TypeScript `*.d.ts` files are included, so both TS and JS users can make use of the package.
    - I started experimenting with rollup -- I couldn't get `@rollup/plugin-typescript` to generate `*.d.ts` files, but `@wessberg/rollup-plugin-ts` seems to work
- [ ] Make sure the `math.css` file is included along with the package
- [ ] Decide which features form the "core" of `prosemirror-math` and which are optional 
- [ ] Document the public API
- [ ] Document or resolve known issues with the current prosemirror-math implementation

I'll work on some of these changes, and update here as I make progress.  If you don't mind, I'll probably ping you a bit later for some more specific feedback about how the plugins should be exposed.  I'd like to make `prosemirror-math` as user-friendly as possible, so anything you can tell me about your specific use case (your preferred way to call the plugin, the customization options you'd like to see, etc.) would be helpful!

**Comment by rowanc1** [comment]
I just put a PR up with the work that I did to get it starting to work in my repository.

Most of these are actually checked off in that! :) But with a couple other changes that I can back out...

**Comment by rowanc1** [comment]
I left some comments in the Review in #9, they might be helpful?! I can take it further or let it be inspiration. :) 

I just put in demos into my editor: 
Demo: https://curvenote.github.io/editor/
Action: https://github.com/curvenote/editor/blob/main/.github/workflows/demo.yml

It should be able to build the action and then you can host it on gh-pages or push to somewhere else. A gh-action that also lints and/or tests some things would likely be helpful! Which would help with #7 

Let me know if I can take on any of this!

**Comment by benrbray** [comment]
Sorry for the radio silence!  Now you can do `npm install @benrbray/prosemirror-math` !  See also the [npm page](https://www.npmjs.com/package/@benrbray/prosemirror-math).
